import os
from datetime import datetime
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

def create_application_excel(form_data=None):
    """
    Create Application Excel file
    """
    wb = Workbook()
    ws = wb.active
    
    # Set worksheet title based on Application Name input
    if form_data and 'applicationName' in form_data and form_data['applicationName']:
        # Use the Application Name as worksheet title (max 31 characters for Excel)
        worksheet_title = form_data['applicationName'][:31]
        # Replace invalid characters for worksheet names
        invalid_chars = ['\\', '/', '*', '?', ':', '[', ']']
        for char in invalid_chars:
            worksheet_title = worksheet_title.replace(char, '_')
        ws.title = worksheet_title
    else:
        ws.title = "Application"

    # Define headers
    headers = [
        "Sr. No.", "Questionnaire/Points", "Compliance/Non-Compliance/Not Applicable",
        "Observation (Short/Brief)", "Risk Factor", "Observation", "Impact", "Recommendation"
    ]

    # Define column widths
    column_widths = {
        'A': 10, 'B': 50, 'C': 20, 'D': 30, 'E': 20, 'F': 50, 'G': 50, 'H': 50
    }

    for col, width in column_widths.items():
        ws.column_dimensions[col].width = width

    # Define border style
    thin_border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    # Apply header styling
    header_font = Font(name='Calibri', size=12, color='FFFFFF', bold=True)
    header_fill = PatternFill(start_color='366092', end_color='366092', fill_type='solid') # Blue
    header_alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
    
    for col_num, header_title in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_num, value=header_title)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment
        cell.border = thin_border

    # Application Questions
    questions = [
        "Verify whether the password is displayed in an encrypted format or not?",
        "Verify whether the password rules are implemented on pages like signup, forgot password, and change password?",
        "Whether the user is allowed to log in with an old password after a password change?",
        "Whether passwords are stored in cookies or not?",
        "Is session timeout functionality properly working?",
        "Whether the user can upload a file?",
        "Whether the web application is using HTTPS (SSL certificate) or not?",
        "Does the software lock the user ID if it is used for 3 unsuccessful login attempts?",
        "Does the software allow the same user to be both maker and checker of the same transaction?",
        "Whether proper consistency/concurrency of user inputs is maintained if two users access the same record simultaneously?",
        "Whether the key data is authorized by an appropriate level of users and kept secure?",
        "Are the transactions for the day identifiable?",
        "Is there an event log for the batch processes?",
        "Whether the software maintains an audit trail to uniquely trace any modification/deletion/addition with user ID?",
        "Whether the format, contents, accuracy, and utility of the reports generated by the system are appropriate?",
        "Does the output contain key control information necessary to validate the accuracy and completeness?",
        "Is manual intervention possible when data passes from one process to another?",
        "Does the software prevent the same user from performing both the functions of entering a transaction and verifying the same?",
        "If transactions are authorized manually, are there controls to ensure that?",
        "Is Change Management procedure including testing & documentation of change followed?",
        "Verify whether the wrong password policy is defined or not?",
        "Whether 2FA is available or not?",
        "What happens if a user deletes cookies while on the site?",
        "Whether the user gets redirected to a custom error page during functionality failure?",
        "Does the application open in a different browser?",
        "Whether the application is responsive or not?",
        "Whether the error messages display any important information?",
        "Whether negative numbers are allowed for numeric fields?",
        "Whether a confirmation message is displayed for update and delete operations?",
        "Whether a pop-up message displays if the data reaches the maximum size of the field?",
        "Whether special characters are accepted in input fields?",
        "Whether the functionality of the buttons is available and properly working?",
        "Whether error messages are displayed correctly?",
        "Does the software allow the creation of user IDs with the same name more than once?",
        "Is there a mechanism to identify and remove outdated libraries, frameworks, or plugins that introduce vulnerabilities?",
        "Is data transmission encrypted using TLS 1.2/1.3 to prevent interception?",
        "Is CBS backup ensured? What is the duration of backup? Whether backup is secure?",
        "Does the software maintain password history?",
        "Are all asset movements supported by suitable written authorizations?",
        "Whether input validation for name fields is available?",
        "Whether input validation for numeric fields is available?"
    ]

    # Risk Factors (provided by user)
    risk_factors = [
        "Critical", "High", "High", "High", "High", "High", "High", "High", "High", "High", 
        "High", "High", "High", "High", "High", "High", "High", "High", "High", "High", "Medium", 
        "Medium", "Medium", "Medium", "Medium", "Medium", "Medium", "Medium", "Medium", 
        "Medium", "Medium", "Medium", "Medium", "Medium", "Medium", "Medium", "Medium", "Medium", "Medium", "Low", "Low"
    ]

    # Mapping of form field names to question numbers
    question_mapping = {
        "appPasswordEncrypted": 1,
        "appPasswordRules": 2,
        "appOldPasswordLogin": 3,
        "appPasswordInCookies": 4,
        "appSessionTimeout": 5,
        "appFileUpload": 6,
        "appHTTPS": 7,
        "appAccountLockout": 8,
        "appMakerCheckerSame": 9,
        "appConcurrencyControl": 10,
        "appKeyDataAuthorization": 11,
        "appTransactionIdentifiable": 12,
        "appBatchEventLog": 13,
        "appAuditTrail": 14,
        "appReportFormat": 15,
        "appOutputControlInfo": 16,
        "appManualIntervention": 17,
        "appMakerCheckerPrevention": 18,
        "appManualAuthorizationControl": 19,
        "appChangeManagementProcedure": 20,
        "appWrongPasswordPolicy": 21,
        "app2FA": 22,
        "appCookieDeletion": 23,
        "appCustomErrorPage": 24,
        "appBrowserCompatibility": 25,
        "appResponsive": 26,
        "appErrorMessages": 27,
        "appNegativeNumbers": 28,
        "appConfirmationMessage": 29,
        "appMaxSizePopup": 30,
        "appSpecialCharacters": 31,
        "appButtonFunctionality": 32,
        "appErrorDisplay": 33,
        "appDuplicateUserID": 34,
        "appOutdatedLibrariesMechanism": 35,
        "appDataTransmissionEncrypted": 36,
        "appCBSBackupEnsured": 37,
        "appPasswordHistory": 38,
        "appAssetMovementAuth": 39,
        "appNameFieldValidation": 40,
        "appNumericFieldValidation": 41
    }

    # Question responses data
    question_responses = {
        1: {  # appPasswordEncrypted
            'compliance': {'a': 'Compliance', 'b': 'Passwords encrypted and masked.', 'd': 'Application stores passwords using strong hashing with salt and masks input fields during login or registration. No clear-text password is displayed or retrievable.', 'f': 'Prevents unauthorized disclosure of user credentials and maintains data confidentiality.', 'h': 'Periodically review password encryption methods and ensure compliance with OWASP Password Storage Guidelines.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Password was displayed in an encrypted format.', 'd': 'It was observed that application password was not displayed in an encrypted format. This application sends the user credentials unencrypted while login applications. The credentials travel in plain text format.', 'f': 'An attacker can sniff the network and get the credentials of the user without his knowledge as the credentials travel unencrypted. An attacker can get access to the valid user account and can view the transaction details and can change the password of the valid user.', 'h': 'It is recommended to encrypt the credentials and any sensitive information before transferring to the server for validation and to have a Strong Encryption algorithm for encryption.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        2: {  # appPasswordRules
            'compliance': {'a': 'Compliance', 'b': 'Strong password policy enforced.', 'd': 'Password complexity, length, and reuse restrictions are enforced on all user authentication interfaces.', 'f': 'Strengthens overall account security by reducing weak credential risks.', 'h': 'Periodically test password policy implementation and ensure enforcement during password resets and registration.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Password rules were not mandated on pages like signup, forgot password, or change password.', 'd': 'It was observed that there were no password rules on pages like signup, forgot password, or change password.', 'f': 'If password rules are not properly implemented on pages such as signup, forgot password, and change password, users may create weak or easily guessable passwords. This increases the risk of account compromise through brute-force or credential-stuffing attacks', 'h': 'It is recommended to verify and enforce password rules across all authentication-related pages, including signup, forgot password, and change password. The system should enforce complexity requirements such as minimum length, use of special characters, numbers, and mixed-case letters.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        3: {  # appOldPasswordLogin
            'compliance': {'a': 'Compliance', 'b': 'User are not allowed to log-in with old passwords after a password change.', 'd': 'Application ensures old passwords become invalid once a user resets credentials, and all sessions are logged out.', 'f': 'Prevents unauthorized access and enhances account integrity.', 'h': 'Maintain real-time session invalidation logic and test periodically.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The old password was not allowed after changing the password.', 'd': 'After updating credentials, previous passwords are still accepted for authentication. Session invalidation is not enforced.', 'f': 'If the old password is allowed even after changing the password and if an attacker gets hold of the old credentials then the attacker can take over the user account by using the old password.', 'h': 'It is recommended to fix this bug where the user can still use the old password and allow only the latest password to be used when logging in.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        4: {  # appPasswordInCookies
            'compliance': {'a': 'Compliance', 'b': 'Passwords not stored in cookies.', 'd': 'Application uses short-lived, encrypted session tokens with Secure and HttpOnly flags set. No passwords are cached or stored client-side.', 'f': 'Reduces risk of credential exposure through cookie theft.', 'h': 'Periodically validate session management headers using security scanners (e.g., Burp, OWASP ZAP).'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Passwords was stored in cookies.', 'd': 'Application stores user credentials or session identifiers in persistent cookies.', 'f': 'Storing passwords in cookies poses a severe security risk, as cookies can be intercepted, modified, or accessed by unauthorized users or malicious scripts. This can lead to credential theft, unauthorized access, and potential compromise of user accounts or sensitive data.', 'h': 'Avoid storing passwords in cookies; instead, use secure session tokens (JWT) with HttpOnly and Secure flags.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        5: {  # appSessionTimeout
            'compliance': {'a': 'Compliance', 'b': 'Session timeout implemented.', 'd': 'User sessions automatically expire after defined inactivity; session tokens become invalid post-timeout.', 'f': 'Minimizes risk of session hijacking and improves account security.', 'h': 'Regularly test session timeout triggers and confirm alignment with security policy.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Session timeout was longer than 10 minutes.', 'd': 'It was observed that the Session timeout was longer than 10 minutes. Session timeout functionality was not properly defined in the application.', 'f': 'Having a session timeout longer than 10 minutes increases the risk of unauthorized access if a user leaves their session unattended. Attackers or unauthorized individuals could misuse an active session to access sensitive information or perform unauthorized transactions.', 'h': 'Enforce session timeouts (up to 10 mins of inactivity) and require re-authentication for sensitive operations.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        6: {  # appFileUpload
            'compliance': {'a': 'Compliance', 'b': 'Secure upload control in place.', 'd': 'Application restricts file types, checks MIME types, scans uploads for malware, and stores them in isolated directories.', 'f': 'Reduces the risk of malicious code execution and file-based attacks.', 'h': 'Periodically test upload validation controls and antivirus scanning efficacy.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The user was able to upload malicious files to the application.', 'd': 'Application allows unrestricted file uploads without proper validation, allowing execution of malicious scripts or large files.', 'f': "If a malicious user uploads file which contains malware, keylogger, spyware or virus then it can compromise the CIA triad of  bank's infrastructure. Thus the bank may face financial, reputational loss.", 'h': 'It is recommended that a user should not be allowed to upload executable, malicious files.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        7: {  # appHTTPS
            'compliance': {'a': 'Compliance', 'b': 'HTTPS enabled and enforced.', 'd': 'All communications are secured via TLS 1.2/1.3 with valid SSL certificates and HSTS configured.', 'f': 'Ensures data confidentiality and integrity during transmission.', 'h': 'Renew SSL certificates before expiry and run periodic SSL configuration audits.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Application was not using HTTPS (SSL certificate).', 'd': 'Application allows unencrypted HTTP connections or has an expired SSL certificate, exposing data in transit.', 'f': 'This may lead to leakage of data including the personal data of customers, which may get compromised. Without an SSL certificate, a secure connection cannot be established, which means that information will not be digitally connected to a cryptographic key and thus all the sensitive data will be exposed to the hacker for theft.', 'h': 'Enforce HTTPS using valid SSL/TLS certificates and implement HSTS headers to prevent downgrade attacks.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        8: {  # appAccountLockout
            'compliance': {'a': 'Compliance', 'b': 'Lockout mechanism enabled.', 'd': 'User accounts are temporarily locked after 3 failed login attempts; reactivation requires verification or timeout.', 'f': 'Prevents brute-force and credential guessing attacks effectively.', 'h': 'Periodically test failed login handling and monitor lockout logs for suspicious patterns.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The software lockout user IDs after 3 consecutive log-on attempts failed.', 'd': 'Application allows unlimited failed login attempts without delay or account lockout, increasing brute-force attack risk.', 'f': 'If the system does not lock out the user id after 3 consecutive failed login attempts then the attacker can perform a password brute force attack to guess the correct credentials. Thus, an attacker can take over an account using the password brute force method.', 'h': 'It is recommended to lock out the user account after consecutive failed login attempts to stop password brute force attacks, but the lockout should not be long enough to cause a DOS attack on real user. '},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        9: {  # appMakerCheckerSame
            'compliance': {'a': 'Compliance', 'b': 'Maker-checker control implemented.', 'd': 'Application enforces role-based restrictions where the maker cannot approve their own transaction.', 'f': 'Strengthens transaction integrity, accountability, and reduces internal fraud risk.', 'h': 'Conduct periodic RBAC reviews to ensure maker-checker mappings remain accurate.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The application allow the same user to be the maker and checker of the transaction.', 'd': 'The same user can create and authorize (verify) a transaction without second-level approval.', 'f': 'Violates dual-control principles, allowing fraudulent or erroneous transactions to bypass verification.', 'h': 'Implement maker-checker segregation — enforce distinct user roles for initiation and approval of sensitive actions.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        10: {  # appConcurrencyControl
            'compliance': {'a': 'Compliance', 'b': 'The system maintains proper consistency and concurrency control when two users access the same record simultaneously.', 'd': 'The application locks records being edited and prevents parallel modifications by other users, ensuring consistency.', 'f': 'Prevents data loss and ensures reliability, maintaining transactional and referential integrity.', 'h': 'Periodically validate concurrency mechanisms during QA testing and production audits.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The consistency of the user input was not maintained if two users are accessing the record at the same time.', 'd': 'The system allows multiple users to access and modify the same record simultaneously, causing overwriting or loss of information.', 'f': 'If both the users are accessing the same data at the same time and consistency is not maintained then it impacts the integrity of the data, and the original data can be lost.', 'h': 'It is recommended that consistency/concurrency of user inputs should be maintained if two users are accessing the same record at the same time.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        11: {  # appKeyDataAuthorization
            'compliance': {'a': 'Compliance', 'b': 'Proper authorization control established.', 'd': 'Key operational data changes are only permitted after verification and approval from designated authorized users.', 'f': 'Ensures that only legitimate, approved modifications are applied, protecting data authenticity and accountability.', 'h': 'Conduct quarterly reviews of user access roles and authorization privileges.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The key data is not authorized by users at the appropriate level and is not kept secure.', 'd': 'Critical business data and transactions can be modified without proper approval or authorization from higher-level users.', 'f': 'If key data is not properly authorized by appropriate users or not kept secure, there is a high risk of unauthorized modification, misuse, or data leakage. This can lead to loss of data integrity, operational disruptions, and potential regulatory non-compliance.', 'h': 'It is recommended that all key data be reviewed and authorized only by users with appropriate approval levels as defined in the organization’s policy. Access to such data should be restricted and protected through proper authentication and encryption mechanisms.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        12: {  # appTransactionIdentifiable
            'compliance': {'a': 'Compliance', 'b': 'Daily transactions clearly identifiable.', 'd': 'Every transaction is recorded with a unique ID and timestamp, allowing easy daily reconciliation and reporting.', 'f': 'Enhances traceability, supports audit readiness, and strengthens operational monitoring.', 'h': 'Regularly validate date/time synchronization across systems to maintain transaction accuracy.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The transaction of the day were not identifiable.', 'd': 'The system does not maintain a clear timestamp or transaction identifier for daily operations, making chronological tracing difficult.', 'f': 'If the transaction of the day is not identifiable, then it will be hard to investigate fake transactions or trail of the fake transactions, thus bank will not be able to find the details regarding the transactions for the investigation purpose.', 'h': 'It is recommended that transactions of the day should be identifiable for forensics purposes so that banks can investigate the root cause by looking at the reports of transactions done on that particular day.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        13: {  # appBatchEventLog
            'compliance': {'a': 'Compliance', 'b': 'Batch event logging implemented.', 'd': 'All scheduled and manual batch jobs are logged, capturing key execution events and exceptions.', 'f': 'Facilitates error diagnosis, ensures accountability, and provides audit trail visibility for automated operations.', 'h': 'Periodically review and archive event logs as per retention policy.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'There was no event log for the batch processes.', 'd': 'It was observed that there was no event log for the batch processes.', 'f': 'If there is no event log for the batch process then it will be hard for the bank to investigate or debug the issue with the batch process, also it will be helpful to have batch process logs if any financial fraud or cyber attack occurs on that system.', 'h': 'It is recommended that there must be an event log for the batch processes that help solve any issue. It can be helpful to see the transaction trail for fraud investigations.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        14: {  # appAuditTrail
            'compliance': {'a': 'Compliance', 'b': 'Comprehensive audit trail maintained.', 'd': 'The system records all CRUD (Create, Read, Update, Delete) activities with user identification and exact timestamps.', 'f': 'Enables forensic tracking, accountability, and regulatory compliance in investigations.', 'h': 'Regularly review audit logs and configure alerts for suspicious activities.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The software does not maintain logs to trace modification, deletion, or addition with the user id.', 'd': 'Modifications or deletions in the system are not logged with corresponding user IDs and timestamps.', 'f': 'If the attacker or the rogue user deletes or adds a new admin account in the system for malicious purposes, then without the audit trails the forensic team will have a hard time finding the root cause of mishaps and the bank will be unable to find that attacker.', 'h': 'It is recommended that the bank maintains an audit trail to trace any modification, deletion, or addition with the user id. '},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        15: {  # appReportFormat
            'compliance': {'a': 'Compliance', 'b': 'Reports accurate and well-structured.', 'd': 'Reports are consistent, complete, and align with source data. Validation checks ensure field accuracy and correct calculations.', 'f': 'Enhances operational efficiency and ensures reliability in decision-making and regulatory reporting.', 'h': 'Periodically test report templates and reconcile data with source systems to maintain accuracy.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The format, contents, and accuracy of the reports generated by the system were appropriate.', 'd': 'Reports generated contain missing fields, incorrect data formats, or inconsistencies with source records.', 'f': 'If the reports are not properly generated by the system then the bank will not be able to properly verify the transactions and critical data which will impact the day-to-day business of the bank. It can cause financial damage to the bank.', 'h': 'It is recommended that the system generates appropriate reports that can ease the day-to-day operations of the bank.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        16: {  # appOutputControlInfo
            'compliance': {'a': 'Compliance', 'b': 'Output includes verification controls.', 'd': 'Each system output contains validation metadata such as record counts, hash totals, and timestamps for accuracy verification.', 'f': 'Supports data validation, ensures completeness, and enhances confidence in output reliability.', 'h': 'Periodically verify that control totals match expected values during data transfers.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Key information was present to validate the accuracy and completeness of operations performed.', 'd': 'It was observed that key information was present to validate the accuracy and completeness of operations performed.', 'f': 'If the output does not contain key control information to validate the accuracy and completeness of the transactions then it will be hard to verify the transactions for investigations purposes or debug any issue with the operations. ', 'h': 'It is recommended that output should contain key control information to validate the accuracy and completeness of the operations.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        17: {  # appManualIntervention
            'compliance': {'a': 'Compliance', 'b': 'Manual intervention restricted.', 'd': 'Data exchange between modules is automated and authenticated, with manual overrides requiring authorized approval.', 'f': 'Protects data integrity and minimizes manipulation risk during process transitions.', 'h': 'Periodically review process automation and access control configurations.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'When data is passed from one process to another, manual intervention was not possible.', 'd': 'Data transferred between system modules can be manually altered without authorization or audit logging.', 'f': 'If manual intervention is possible then it can impact the integrity of the data being passed from one process to another. The attacker can also try to intervene every time, impacting the Integrity and availability of the data.', 'h': 'Automate inter-process data transfers and restrict manual overrides with approvals and audit trails.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        18: {  # appMakerCheckerPrevention
            'compliance': {'a': 'Compliance', 'b': 'The software restricts users from performing both transaction entry and verification functions.', 'd': 'Application enforces maker-checker functionality where creation and approval are handled by separate authorized roles.', 'f': 'Ensures segregation of duties, reducing the risk of errors and fraudulent activities.', 'h': 'Review and test user role assignments periodically to maintain segregation of duties.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The application do not allow the same user to enter and verify the transaction.', 'd': 'The same user can both create and approve transactions, bypassing dual authorization controls.', 'f': 'If the same user is the maker, and checker of the transaction then that user can easily do fake transactions to commit financial fraud. Thus banks will suffer financial damages.', 'h': 'It is recommended that software should not allow the same user to be the maker and checker of the same transaction.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        19: {  # appManualAuthorizationControl
            'compliance': {'a': 'Compliance', 'b': 'Manual transaction authorizations are governed by defined controls and approval procedures.', 'd': 'Manual transaction authorization is verified by checker approval, ensuring accountability and reducing fraud risk.', 'f': 'Maintains integrity of financial transactions with proper maker-checker validation.', 'h': 'Continue periodic verification of manual control workflows through audit reviews.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Manual authorization lacks validation control.', 'd': 'It was observed that transactions authorized manually were not properly validated by any secondary control mechanism or maker-checker verification.', 'f': 'If the transactions are authorized manually it will lead to operational type risk, which is low for simple business operations such as retail banking and asset management, and higher for operations such as sales and trading. Losses that occur due to human error include internal fraud or mistakes made during transactions.', 'h': 'It is recommended that manual transactions should not be authorized/allowed and if allowed, implementing authoritative controls should be ensured.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        20: {  # appChangeManagementProcedure
            'compliance': {'a': 'Compliance', 'b': 'The change management procedure, including testing and documentation of changes in the Application, was followed properly.', 'd': 'Change Management procedures, including testing and proper documentation of changes, are followed as per the bank’s policy.', 'f': 'Ensures controlled implementation of changes, reduces operational risks, and maintains system stability and auditability.', 'h': 'The bank should continue to enforce formal change management controls, including approval workflows, testing evidence, and post-implementation reviews, to ensure accountability and minimize potential disruptions.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The change management procedure, including testing and documentation of changes in the Application, was not followed.', 'd': 'It was observed that formal change management procedures are not consistently followed. Some changes were implemented without proper documentation, testing, or approval from authorized personnel.', 'f': 'Lack of structured change management may result in system downtime, application malfunction, data integrity issues, and potential security breaches, leading to regulatory non-compliance.', 'h': '''The bank should implement a formal change management framework that includes:

1. Proper documentation, testing, and approval before implementing any changes.

2. Maintaining a change register with details of request, testing results, and approvals.'''},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        21: {  # appWrongPasswordPolicy
            'compliance': {'a': 'Compliance', 'b': 'Wrong password policy implemented.', 'd': 'The application enforces account lockout after multiple failed login attempts, preventing brute-force attacks.', 'f': 'Reduces account compromise risk and strengthens authentication security.', 'h': 'Periodically review the password policy to ensure alignment with security standards.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The wrong password policy was defined.', 'd': 'It was observed that for password policy was wrongly defined. Passwords less than 8 characters in length were allowed, without any special characters or combination of uppercase and lowercase characters.', 'f': 'A weakly defined password policy allowing passwords shorter than eight characters and lacking complexity significantly increases the risk of unauthorized access.', 'h': 'It is recommended that a strong password policy be implemented, enforcing a minimum length of at least eight characters and requiring a combination of uppercase letters, lowercase letters, numbers, and special characters.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        22: {  # app2FA
            'compliance': {'a': 'Compliance', 'b': '2FA enabled.', 'd': 'Users are required to verify login through OTP, email, or mobile-based second-factor authentication.', 'f': 'Significantly enhances account security and prevents unauthorized logins.', 'h': 'Ensure 2FA remains mandatory for all administrative and sensitive operations.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Two-Step Verification was not available on Login Page.', 'd': 'The system allows access using only username and password, without additional authentication layers.', 'f': 'It will be easy for unauthorized parties to gain access to the accounts, which increases the risk of fraud. Without Two-factor authentication (MFA), cybercriminals can much more easily gain access to an account. Once the username and password are acquired, every transaction will be treated as valid, and basic security measures cannot prevent it. Authenticity will not be maintained.', 'h': 'It is recommended to enable Two-Step Verification on Login Page for better security.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        23: {  # appCookieDeletion
            'compliance': {'a': 'Compliance', 'b': 'Session reauthentication enforced on cookie deletion.', 'd': 'Application correctly invalidates sessions and prompts users to log in again after cookies are deleted.', 'f': 'Prevents unauthorized session continuity, enhancing session security.', 'h': 'Regularly test session handling to ensure consistent enforcement across browsers.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Session not invalidated after cookie deletion.', 'd': 'When users delete cookies mid-session, the application continues active access instead of forcing reauthentication.', 'f': 'If the user is not logged out after deleting cookies means that the session was not terminated properly after deleting cookies. An attacker can use the token replay attack and reuse the session identifier as sessions are not properly terminated.', 'h': 'It is recommended that the session should terminate properly when cookies are deleted for that particular domain.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        24: {  # appCustomErrorPage
            'compliance': {'a': 'Compliance', 'b': 'Custom error page implemented.', 'd': 'The application redirects users to predefined error pages that display generic messages without exposing technical information.', 'f': 'Prevents information leakage during unexpected failures.', 'h': 'Periodically review and test error-handling configurations.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The user was redirected to the error page during the functionality failure.', 'd': 'The application displays raw server error details rather than redirecting users to a custom error page.', 'f': 'If the user is not redirected to the error page during the functionality failure and custom error pages are not displayed then critical server information or framework information can be leaked and attackers can use this information to attack the application.', 'h': 'It is recommended that the user should get redirected to custom error pages on functionality failure so that default error pages do not disclose sensitive information.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        25: {  # appBrowserCompatibility
            'compliance': {'a': 'Compliance', 'b': 'Browser compatibility ensured.', 'd': 'Application has been tested and works correctly across Chrome, Edge, and Firefox, with consistent layout and functionality.', 'f': 'Users can access the application from multiple browsers without operational issues, improving usability and accessibility.', 'h': 'Regularly perform cross-browser tests after updates to maintain compatibility.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The application does opens in different browsers.', 'd': 'The application fails to render or function properly on certain browsers such as Firefox or Edge, causing broken UI elements and unresponsive features.', 'f': 'Users may experience inconsistent functionality, reducing accessibility and productivity, and potentially losing critical operations.', 'h': 'Conduct cross-browser testing and implement standards-compliant code to ensure consistent performance across all popular browsers.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        26: {  # appResponsive
            'compliance': {'a': 'Compliance', 'b': 'Application is responsive.', 'd': 'Pages dynamically adjust to screen size and orientation, providing a consistent experience across devices.', 'f': 'Ensures smooth user interaction and accessibility, improving operational efficiency on mobile and desktop.', 'h': 'Continuously test responsiveness with new releases and device variations.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Application not responsive.', 'd': 'Web pages do not adapt to different screen sizes, causing distorted layouts on mobile or tablet devices.', 'f': 'Poor responsiveness reduces usability, accessibility, and user satisfaction, and may prevent users from completing tasks efficiently.', 'h': 'Implement responsive design using CSS frameworks like Bootstrap and test on multiple devices and screen resolutions.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        27: {  # appErrorMessages
            'compliance': {'a': 'Compliance', 'b': 'Error messages do not display sensitive or system-related information.', 'd': 'Users see only generic error messages without sensitive system information, while detailed logs are securely maintained for developers.', 'f': 'Prevents information leakage and reduces the risk of exploitation.', 'h': 'Periodically review error handling to ensure no sensitive information is disclosed.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The error messages display sensitive information about the application.', 'd': 'It was observed that Application error messages display sensitive information about the language used to create an application and the error flows. Error messages can help to understand the architecture of the application.', 'f': 'An attacker can grab the information and understand the architecture of the product by the error messages and find the appropriate exploitation and try to attack the servers.', 'h': 'It is recommended that the application should not contain error messages and if any error occurs it should not show important information.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        28: {  # appNegativeNumbers
            'compliance': {'a': 'Compliance', 'b': 'Numeric input validation implemented.', 'd': 'Application restricts negative values in fields that require only positive numbers.', 'f': 'Ensures accurate data entry and prevents calculation errors.', 'h': 'Test input validation rules during QA to maintain correctness.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Negative Numbers were accepted in input fields.', 'd': 'Numeric fields accept negative values even in fields where only positive values are valid, leading to incorrect data entries.', 'f': 'Causes data inconsistencies, calculation errors, and potential reporting issues.', 'h': 'Implement input validation to restrict negative numbers where inappropriate.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        29: {  # appConfirmationMessage
            'compliance': {'a': 'Compliance', 'b': 'Confirmation messages displayed.', 'd': 'Application prompts users to confirm all updates and deletions before proceeding.', 'f': 'Reduces accidental data changes and increases user accountability.', 'h': 'Regularly test confirmation mechanisms to ensure they are functional for all critical actions.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'A confirmation message was not available for update and delete operations. ', 'd': 'Users can update or delete records without confirmation, increasing the risk of accidental changes or deletions.', 'f': 'If the confirmation message is not displayed for update and delete operations, the application might delete, and update data without verification or confirmation from the user. This way an unauthenticated user may delete sensitive data.', 'h': 'It is recommended that a confirmation message should display for update and delete operations.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        30: {  # appMaxSizePopup
            'compliance': {'a': 'Compliance', 'b': 'Max size validation implemented.', 'd': 'Users receive notifications or warnings when input reaches the maximum allowed field size.', 'f': 'Prevents data truncation and maintains input accuracy.', 'h': 'Periodically verify that all input fields enforce length restrictions correctly.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'If the data reaches the maximum size of the field, the field does not stop accepting inputs.', 'd': 'Application does not notify users when field input reaches maximum length, causing truncation or errors.', 'f': 'Can result in incomplete or corrupted data entries and user confusion. Usually, this problem is caused by a Vulnerable password hashing implementation. When a long password or  long  input field message is sent, the password hashing or taking input process will result in CPU and memory exhaustion for  encrypting the data of the long string. Sometimes the buffer overflow attacks can also happen if the  input size is greater than   the buffer size.', 'h': 'Implement real-time validation and display pop-up messages when maximum input length is reached.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        31: {  # appSpecialCharacters
            'compliance': {'a': 'Compliance', 'b': 'Input validation for special characters enforced.', 'd': 'Application sanitizes all inputs and blocks inappropriate special characters, preventing injection and data corruption.', 'f': 'Protects against injection attacks and ensures data consistency.', 'h': 'Regularly test input fields for compliance with validation rules.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Special characters were accepted in input fields.', 'd': 'Certain input fields, such as name, ID, or description fields, accept special characters that should be restricted.', 'f': "As the special characters are allowed in the input field, there are increased chances of cyber-attacks like Cross-site scripting (XSS) and SQL Injection (SQLi). The most severe XSS attacks involve the disclosure of the user's session cookie, allowing an attacker to hijack the user's session and take over the account. In SQLi, an attacker can bypass authentication and authorization of a web page or web application and retrieve the content of the entire SQL database.", 'h': 'It is recommended to implement a filter for the special characters in the input fields.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        32: {  # appButtonFunctionality
            'compliance': {'a': 'Compliance', 'b': 'All buttons functional.', 'd': 'Each button performs its intended action, provides feedback, and maintains expected workflow continuity.', 'f': 'Enhances usability and ensures reliable task completion.', 'h': 'Include button functionality in regression testing with every release.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Functionality of the buttons available and properly working.', 'd': 'Some buttons are unresponsive or fail to perform intended actions when clicked, disrupting user workflows.', 'f': 'If the buttons are not functioning then bank employees will not be able to utilize the application with full efficiency, thus it will decrease the productivity of bank employees and the bank will face financial loss due to improper functioning of the application.', 'h': "It is recommended that testing of buttons' functionality must be done to verify that the application is working properly."},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        33: {  # appErrorDisplay
            'compliance': {'a': 'Compliance', 'b': 'Error messages are displayed correctly with appropriate user-friendly information.', 'd': 'Application displays clear, generic messages to users while detailed technical errors are logged securely.', 'f': 'Prevents information disclosure and improves user guidance.', 'h': 'Periodically review error handling for effectiveness and security.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The Error messages were not displayed correctly.', 'd': 'Errors display internal details or vague messages that confuse users instead of guiding corrective action.', 'f': "If the error messages are not displayed correctly then the user will not be able to use the application properly, thus it will impact the bank's day-to-day function and eventually decrease bank's productivity.it can also help attackers in attacking the application if the error message contains important information regarding application, database , framework and its version.", 'h': 'It is recommended that error messages should be displayed correctly to enhance the usability of the software and increase productivity.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        34: {  # appDuplicateUserID
            'compliance': {'a': 'Compliance', 'b': 'Unique usernames enforced.', 'd': 'Application restricts creation of duplicate usernames, ensuring each user ID is distinct and traceable.', 'f': 'Strengthens auditability and user accountability.', 'h': 'Periodically validate uniqueness enforcement during testing and audits.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'A new user can be created using the same user IDs name.', 'd': 'The system permits creation of multiple accounts with the same username, resulting in ambiguous user identification.', 'f': 'Causes accountability issues, audit trail conflicts, and may allow unauthorized access or errors in transaction approvals.', 'h': 'Enforce unique username constraints at account creation and implement system checks to prevent duplication.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        35: {  # appOutdatedLibrariesMechanism
            'compliance': {'a': 'Compliance', 'b': 'The bank have a defined mechanism to identify and remove outdated libraries, frameworks, or plugins used in its applications.', 'd': 'It was observed that the bank has a defined mechanism to periodically identify and remove outdated libraries, frameworks, and plugins. This process helps ensure that only updated and secure components are used, reducing the risk of vulnerabilities within the system.', 'f': 'Ensures use of updated and secure components, reducing vulnerabilities and enhancing application security.', 'h': 'The bank should continue regular reviews of software components and implement automated vulnerability scanning tools to promptly detect and replace outdated or insecure libraries. This will further strengthen the security and stability of applications.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The bank does not have a defined mechanism to identify and remove outdated libraries, frameworks, or plugins used in its applications.', 'd': 'It was observed that there is no defined mechanism or periodic review process in place to identify and remove outdated or vulnerable software components, such as libraries, frameworks, or plugins used in applications.', 'f': 'The absence of a structured process to monitor and update third-party components increases the risk of exploiting known vulnerabilities that could compromise application integrity, lead to data breaches, or allow unauthorized access to banking systems. It also exposes the bank to regulatory and reputational risks.', 'h': 'The bank should establish a formal mechanism to regularly monitor, identify, and update or remove outdated libraries, frameworks, and plugins. This process should be integrated into the change management framework and include periodic vulnerability scans, dependency management tools, and patch verification reports.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        36: {  # appDataTransmissionEncrypted
            'compliance': {'a': 'Compliance', 'b': 'Data transmission is encrypted using TLS 1.2/1.3.', 'd': 'Data transmission between systems is encrypted using TLS 1.2/1.3 protocols to ensure secure communication.', 'f': 'Prevents data interception and unauthorized access during transmission, ensuring confidentiality and integrity of sensitive information.', 'h': 'The bank should continue enforcing the use of strong encryption protocols and periodically review configurations to disable deprecated versions and maintain compliance with security standards.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Data transmission is not encrypted using TLS 1.2/1.3, increasing the risk of data interception.', 'd': 'It was observed that data transmission between certain systems and applications is not encrypted using TLS 1.2 or higher. Some services still allow connections using older or insecure protocols (e.g., TLS 1.0/1.1 or HTTP).', 'f': 'Unencrypted or weakly encrypted data transmission may lead to data interception, man-in-the-middle attacks, or unauthorized access to sensitive information, including customer and banking data.', 'h': '''The bank should:

1. Enforce TLS 1.2 or TLS 1.3 for all internal and external data communications.

2. Disable insecure protocols such as SSL, TLS 1.0, and TLS 1.1.'''},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        37: {  # appCBSBackupEnsured
            'compliance': {'a': 'Compliance', 'b': 'CBS backup is ensured on a regular basis. The duration and frequency of backups are clearly defined.', 'd': 'Core Banking System (CBS) backups are taken regularly as per the bank’s backup policy, and stored securely to prevent unauthorized access or data loss.', 'f': 'Ensures data availability, integrity, and quick restoration in case of system failure or disaster.', 'h': 'The bank should periodically test backup restoration and maintain offsite or cloud copies to ensure data recoverability and resilience against potential disruptions.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'CBS backup process is not ensured on a regular basis. The duration and frequency of backups are not clearly defined or documented.', 'd': 'It was observed that Core Banking System (CBS) backups are taken on a regular basis; however, the details regarding backup frequency, retention period, and restoration testing are not formally documented. In some instances, the backup media were found to be stored without adequate physical or logical security controls.', 'f': 'Improperly managed or unsecured backups may lead to data loss, corruption, or unavailability of CBS data during system failure or cyber incidents. This could severely disrupt banking operations and affect compliance with regulatory requirements.', 'h': '''The bank should ensure that CBS backups are performed regularly and securely, with proper documentation of frequency, retention, and restoration procedures. All backups should be encrypted and stored in a secured offsite location, with periodic restoration testing to confirm data integrity and recoverability.'''},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        38: {  # appPasswordHistory
            'compliance': {'a': 'Compliance', 'b': 'Password history maintained.', 'd': 'System prevents reuse of previous passwords according to policy, ensuring stronger account security.', 'f': 'Reduces risk of compromised credentials and enforces robust password practices.', 'h': 'Regularly review password history enforcement and update policy as per security standards.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'The application does not maintain a password history.', 'd': 'Users can reuse previous passwords without restrictions, reducing password policy effectiveness.', 'f': "As the history of the password is not retained, the user can use a repetitive password for his ease. But this easy practice makes the task of guessing or cracking passwords much easy for an attacker. Thus an attacker can compromise the user account after guessing the user password which will impact the security posture of the bank's infrastructure.", 'h': 'Maintain password history for a configurable number of previous passwords (e.g., last 3–5) to prevent reuse.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        39: {  # appAssetMovementAuth
            'compliance': {'a': 'Compliance', 'b': 'Written authorization enforced for all asset movements.', 'd': 'Application requires formal approval for every asset transaction, ensuring accountability and traceability.', 'f': 'Prevents unauthorized access or misuse of assets.', 'h': 'Periodically audit asset movement logs to ensure proper authorization compliance.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'All asset movements were supported by written authorizations.', 'd': 'It was observed that all asset movements were not supported by written authorizations.', 'f': 'If the asset movements are not supported by written authorizations, then upon asset damage or loss of an asset no data will be available regarding the asset.', 'h': 'It is recommended that all the asset movements are supported by written authorization to clarify who authorized the asset movement and to whom the report should be submitted in case an asset is damaged or lost.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        40: {  # appNameFieldValidation
            'compliance': {'a': 'Compliance', 'b': 'Name field validation enforced.', 'd': 'Application enforces rules for name fields, rejecting invalid input and ensuring accurate data capture.', 'f': 'Maintains data consistency and integrity across the system.', 'h': 'Regularly verify validation logic to prevent circumvention and ensure data accuracy.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Numbers were accepted in the Name field. ', 'd': 'Users can input invalid characters (numbers, symbols) in name fields, leading to inconsistent or inaccurate data.', 'f': 'When software does not validate input properly, an attacker is able to craft the input in a form that is not expected by the rest of the application. This will lead to parts of the system receiving unintended input, which may result in altered control flow, arbitrary control of a resource, or arbitrary code execution.', 'h': 'It is recommended to implement validation for the numbers in the name input fields.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        },
        41: {  # appNumericFieldValidation
            'compliance': {'a': 'Compliance', 'b': 'Numeric input validation implemented.', 'd': 'Application enforces numeric validation, ensuring only valid numeric entries are accepted.', 'f': 'Ensures accurate calculations, reporting, and overall system reliability.', 'h': 'Periodically test numeric fields during QA and regression cycles to ensure consistent validation.'},
            'non_compliance': {'a': 'Non-Compliance', 'b': 'Characters were accepted in the Number field.', 'd': 'Users can enter invalid data (non-numeric or negative values) in numeric fields, causing processing errors.', 'f': 'When software does not validate input properly, an attacker is able to craft the input in a form that is not expected by the rest of the application. This will lead to parts of the system receiving unintended input, which may result in altered control flow, arbitrary control of a resource, or arbitrary code execution.', 'h': 'It is recommended to implement validation for the characters in the Number input fields.'},
            'not_applicable': {'a': 'Not Applicable', 'b': 'Not Applicable', 'd': 'Not Applicable', 'f': 'Not Applicable', 'h': 'Not Applicable'}
        }
    }

    # Add Application Name at the top
    if form_data and 'applicationName' in form_data:
        app_name = form_data.get('applicationName', '')
        if app_name:
            ws.merge_cells('A1:H1')
            title_cell = ws.cell(row=1, column=1, value=f"Application Assessment: {app_name}")
            title_cell.font = Font(name='Calibri', size=14, bold=True)
            title_cell.alignment = Alignment(horizontal='center', vertical='center')
            title_cell.fill = PatternFill(start_color='E6F3FF', end_color='E6F3FF', fill_type='solid')
            title_cell.border = thin_border
            
            # Move headers to row 2
            for col_num, header_title in enumerate(headers, 1):
                cell = ws.cell(row=2, column=col_num, value=header_title)
                cell.font = header_font
                cell.fill = header_fill
                cell.alignment = header_alignment
                cell.border = thin_border
            
            # Populate questions starting from row 3
            start_row = 3
        else:
            start_row = 2
    else:
        start_row = 2

    # Populate questions and Sr. No.
    for i, question in enumerate(questions, start_row):
        # Sr. No. with center alignment
        sr_no_cell = ws.cell(row=i, column=1, value=i-start_row+1)
        sr_no_cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
        ws.cell(row=i, column=2, value=question)  # Questions

    # Risk colors
    risk_colors = {
        'Critical': '8B0000',  # Dark Red
        'High': 'FF0000',      # Red
        'Medium': 'FFA500',    # Orange
        'Low': '008000'        # Green
    }

    # Populate data based on user input
    for i, question in enumerate(questions, start_row):
        # Get user input for this question
        question_num = i - start_row + 1
        user_input = None
        
        if form_data:
            # Find the corresponding form field
            for field_name, q_num in question_mapping.items():
                if q_num == question_num:
                    user_input = form_data.get(field_name, 'not_applicable')
                    break
        
        if not user_input:
            user_input = 'not_applicable'
        
        # Get response data
        if question_num in question_responses:
            response_data = question_responses[question_num].get(user_input, question_responses[question_num]['not_applicable'])
            
            # Populate columns C, D, F, G, H
            ws.cell(row=i, column=3, value=response_data['a'])  # Compliance/Non-Compliance/Not Applicable
            ws.cell(row=i, column=4, value=response_data['b'])  # Observation (Short/Brief)
            ws.cell(row=i, column=6, value=response_data['d'])  # Observation
            ws.cell(row=i, column=7, value=response_data['f'])  # Impact
            ws.cell(row=i, column=8, value=response_data['h'])  # Recommendation
            
            # Apply alignment to these columns
            for col in [3, 4, 6, 7, 8]:
                cell = ws.cell(row=i, column=col)
                cell.alignment = Alignment(horizontal='left', vertical='center', wrap_text=True)
                cell.border = thin_border
        
        # Populate Risk Factor (column E) with color coding
        if question_num <= len(risk_factors):
            risk_factor = risk_factors[question_num - 1]
            risk_cell = ws.cell(row=i, column=5, value=risk_factor)
            risk_cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
            risk_cell.border = thin_border
            
            # Apply color coding
            if risk_factor in risk_colors:
                risk_cell.fill = PatternFill(start_color=risk_colors[risk_factor], end_color=risk_colors[risk_factor], fill_type='solid')
                risk_cell.font = Font(name='Calibri', size=11, color='FFFFFF', bold=True)
            else:
                risk_cell.font = Font(name='Calibri', size=11, color='FFFFFF', bold=True)
    
    # Apply general formatting to all cells
    for row in range(1, len(questions) + start_row):
        for col in range(1, 9):
            cell = ws.cell(row=row, column=col)
            if row > (start_row - 1):  # Skip header row(s)
                cell.border = thin_border
                if col in [1, 3, 5]:  # Sr. No., Compliance, Risk Factor - center aligned
                    cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
                else:  # Other columns - left aligned
                    cell.alignment = Alignment(horizontal='left', vertical='center', wrap_text=True)
                
                # Only apply default font if it's not the Risk Factor column (column 5)
                if col != 5:  # Don't override Risk Factor column formatting
                    cell.font = Font(name='Calibri', size=11)
            # Set row height for wrapped text
            ws.row_dimensions[row].height = 30
    
    # Generate filename based on worksheet name (applicationName)
    if form_data and 'applicationName' in form_data and form_data['applicationName']:
        # Use the Application Name as filename (same as worksheet name logic)
        filename_base = form_data['applicationName'].strip()
        # Replace invalid filename characters (Windows file system restrictions)
        invalid_filename_chars = ['\\', '/', ':', '*', '?', '"', '<', '>', '|']
        for char in invalid_filename_chars:
            filename_base = filename_base.replace(char, '_')
        # Remove multiple consecutive underscores
        while '__' in filename_base:
            filename_base = filename_base.replace('__', '_')
        # Remove leading/trailing underscores and whitespace
        filename_base = filename_base.strip('_').strip()
        # Ensure filename is not empty
        if not filename_base:
            filename_base = "Application Review"
        filename = f"{filename_base}.xlsx"
    else:
        filename = "Application Review.xlsx"
    
    filepath = os.path.join('static', 'uploads', filename)
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    
    wb.save(filepath)
    return filepath, filename

def cleanup_file(filepath):
    """
    Delete the generated Excel file after download
    """
    if os.path.exists(filepath):
        os.remove(filepath)
        print(f"Cleaned up file: {filepath}")
